#!/bin/bash
#
# dotcfg
#
# Author: kilrainebc
# Description: small util for setting up dotfiles

function main () {
  case "$1" in
    --help|-h|help)
      printf "Usage: ./ %s <subcommand>\n" $(basename $0)
      printf "Subcommands:
        install\tinitial install
	reload\tupdates dotfiles
	resize\tresize resolution
	\n"
      printf "Supported Operating Systems:
        arch
        debian
      \n"
      exit 64
    ;;
    install|reload)
      subcmd="$1" 
    ;;
    resize)
      case $2 in
        --help|-h|*help*) 
	  printf "Usage: ./%s resize <device> <mode>\n" $(basename $0)
	  printf "Device:
	  Desktop
	  Laptop
	  \n"
	  printf "Mode:
	  Fullscreen
	  Windowed
	  \n"
    exit 64
	;;
	*)
        subcmd="resize_resolution ${@:2:3}"
	;;
      esac      
    ;;
    *)
      printf "dotcfg: ERROR - Please run ./%s --help\n" $(basename $0)
      exit 64 
    ;;  
  esac

  distro=$( ( lsb_release -ds || cat /etc/*release || uname -om ) 2>/dev/null | head -n1 )
  if [[ $distro == 'NAME="Arch Linux"' ]]; then
    distro='arch'
  # elif [[ $distro == <debians output> ]]; then
  else
    printf "dotcfg: WARN - Automatic Distrobution detection failed!\n"
    while [[ ! -f ./lib/"$distro".bash ]]; do
      read -p "dotcfg: Please supply a distro: " distro
    done
  fi

  source ./lib/$distro.bash
  $subcmd 
}

main $@
